

POST http://localhost:3000/user/create HTTP/1.1
content-type: application/json

{
  "name": "hello",
  "phone": "55667788"
}

### 
GET http://localhost:3000/user/get-by-id?id=2&user=user
### 
GET http://localhost:3000/user/get-list?pageIndex=1&pageSize=20


### 
DELETE  http://localhost:3000/user/delete HTTP/1.1
content-type: application/json

{
  "id": 5
}
### 
DELETE  http://localhost:3000/user/batch-delete HTTP/1.1
content-type: application/json

{
  "userIds": [1,4,5,6,7]
}
### 
PUT http://localhost:3000/user/update HTTP/1.1
content-type: application/json

{
  "id": 7,
  "name": "hihiya~~",
  "phone": "55667788"
}
